steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/wtfffmpeg:$COMMIT_SHA',
      '-t', 'gcr.io/$PROJECT_ID/wtfffmpeg:latest',
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/wtfffmpeg:$COMMIT_SHA']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/wtfffmpeg:latest']

  # Deploy to Cloud Run (alternative to App Engine)
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'wtfffmpeg',
      '--image', 'gcr.io/$PROJECT_ID/wtfffmpeg:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--set-env-vars', 'CLOUD_STORAGE_BUCKET=$_BUCKET_NAME',
      '--memory', '2Gi',
      '--cpu', '1',
      '--timeout', '600',
      '--max-instances', '10'
    ]

# Cloud Build substitutions
substitutions:
  _BUCKET_NAME: 'your-bucket-name'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'