---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: master-v8dr
  annotations:
    # Ensure all requests go to the same revision for consistency
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        # Scale to zero for cost efficiency
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        # Allocate more CPU and memory for FFmpeg operations
        run.googleapis.com/cpu: "2"
        run.googleapis.com/memory: "4Gi"
        # Set timeout for long FFmpeg operations (max 60 minutes)
        run.googleapis.com/timeout: "3600s"
        # Use second generation execution environment
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 1  # Process one video at a time per instance
      containers:
        - image: us-central1-docker.pkg.dev/yt-v8dr/wtfffmpeg-repo/wtfffmpeg
          ports:
            - containerPort: 8080
          env:
            - name: CLOUD_STORAGE_BUCKET
              value: "yt-v8dr-wtfffmpeg-videos"
            - name: SECRET_KEY
              value: "yt-v8dr-secret-2024-production"
          resources:
            limits:
              cpu: "2"
              memory: "4Gi"
          # Health checks
          livenessProbe:
            httpGet:
              path: /_health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /_health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
